### ISSUE TITLE
Testing the Twinkles framework - new users, project approachability etc

### ISSUE THREAD

**Issue by dodelson** [LSSTDESC/Twinkles#182]
Hi, at the SLAC meeting, @drphilmarshall @connolly @richardxdubois  talked about testing the twinkles framework everyone. Jason Poh, a student at Chicago, is interested in doing this. Can someone suggest a test he should try? 
Thanks

**Comment by drphilmarshall** [comment]
We'll discuss this at our meeting today - we need to work on our approachability a bit I think, and Jason can certainly help with that (as long as his expectations are set accordingly :-) ). We do have a test running at Travis now, so *in principle* humans shoudl be able to get up and running too. However, there is an ongoing discussion about  `eups` stuff in #189 that we should perhaps see through before trying to engage Jason. @cdfassnacht is another possible guinea pig for forcing Twinkles to be more approachable.

**Comment by drphilmarshall** [comment]
Related to this issue, @wmwv started a "Request to the project" email for us to discuss at #190 which should lead to a smoother initial setup by new Twinkles contributors.

**Comment by drphilmarshall** [comment]
Scott D's question turned out to be a hard one: we failed to really enable any new analysts before, during or after the Oxford meeting! I conclude that making projects approachable is *hard*. Some hope is on the horizon in the form of the SUIT: I think that should make it far easier to enable drop-in contributions of the kind we need. I'll issue the CI group with looking into a first step in that direction.
