### ISSUE TITLE
CatSim tests prior to Run 3

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/Twinkles#318]
@rbiswas4 @danielsf How is the CatSim tests work going, that we heard you were working on last Thursday?

**Comment by danielsf** [comment]
I think we have something that works and is consistent with "modern" CatSim syntax.  I'll let @rbiswas4 issue the actual pull request, since this got folded into his work updating the supernova tables.

Anyway: you can see the code here:

https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/Sim_instanceCatalogs/python/desc/twinkles/generatePhosimInput.py

**Comment by drphilmarshall** [comment]
Nice! When you make the PR, Rahul, feel free to point us at specific parts
that need review.

**Comment by rbiswas4** [comment]
Closed for now.
