### ISSUE TITLE
Checks on phosim instance catalog generation

### ISSUE THREAD

**Issue by rbiswas4** [LSSTDESC/Twinkles#341]
@TomGlanzman  In the validation branch put a copy of a phosim instance catalog I generated in data/phosimCatalog.dat and spectra files. 
The data/README.md describes the commands used to generate these files (using the code in the setups branch, which is ready to be merged)
The example `examples/notebooks/Using_PhoSimInstanceCatalogData.ipynb` describes how to compare a phosim instance catalog you might generate at SLAC with this. (The location of spectral filenames may be different and so we explicitly allow for ignoring those. It might be an improvement to compare those files with a root directory, but I did not think of that before).

One thing I am somewhat worried about is if we have to further tune tolerances on comparing floats.

@jchiang87 I think it makes sense to have an integration test that will generate the same phosim instance catalog file and make sure that they match (unless we understand that they should not). I could write a test to do this, but it seems like we should be using the script we have already written directly ... and maybe use subprocess to do this? Any opinion on this?

**Comment by jchiang87** [comment]
@rbiswas4 I spent some time yesterday trying to get Jenkins builds going for desc repos.  I'm having some technical problems with getting the directory permissions for the Jenkins account setup (since eups annoyingly wants to write to ~/.eups), but once that's sorted out, this sort of integration test can be added to the test suite and run under Jenkins.   Regarding the test code, we certainly could use `subprocess` to run `generatePhosimInput.py` from the shell, but if that code fails, `unittest` won't be able to catch and report on any exceptions that are raised.  It might be worth encapsulating the code in [lines 120-133](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/bin/generatePhosimInput.py#L120) in a function, then in the test code call that function and then `generateSinglePointing` to create the instance catalog to compare to `data/phosimCatalog.dat`

**Comment by rbiswas4** [comment]
I am splitting this issue into two parts
- [ ] Write a tool for being able to compare phoSim instance catalogs
- [ ] Write a unit test which can be run at generation

The reason for splitting these is the need to have a tool to compare phoSim instance catalogs easily, as pointed out by @TomGlanzman in today's meeting. The work in parsing the instance catalogs into arrays is already done, and can be used. I will try to add the unit test soon.

Two reasons why I started doing this rather than trying `diff`  were
-  when the instance catalogs are run on different machines the floats will be different. I don't believe diff can do numerical tolerances. 
- The user had an ability to change the way the spectra files were written in the catalog using the `--seddir` argument, which might not have been significant. (This is no longer the case with @TomGlanzman 's request for using shorter file names). However, because of this problem, I had written this to read the phosim instance catalog and produce different outputs for each type of catalog (together they make the tabular data non-rectangular), and with the ability to ignore columns while comparing.

**Comment by jchiang87** [comment]
@TomGlanzman This seems to have been done.
