### ISSUE TITLE
phosim simulations should not include effects (sensor, telescope, etc.) that are not modeled by the Stack

### ISSUE THREAD

**Issue by jchiang87** [LSSTDESC/Twinkles#63]

**Comment by drphilmarshall** [comment]
Seems like a good principle to adopt. I will absorb this into the RQ doc.

**Comment by jchiang87** [comment]
@SimonKrughoff Could you list here the effects that you think should be turned off in phosim?

**Comment by SimonKrughoff** [comment]
I would say we turn _off_:
clouds
edge rolloff and midline charge stop
brighter fatter
pointing errors
tree rings?

I would say we leave _on_:
Saturation/blooming
Charge diffusion
Vignetting (don't think we can turn this off anyway)
Sky background (though we may want to tie it to OpSim.  It's not by default)

Other suggestions welcome.

**Comment by drphilmarshall** [comment]
By turning off sky background, I assume you mean not letting PhoSim
generate background, but instead adding background Poisson noise at a level
given by the OpSim outputs, right? This must be standard practice in the
PhoSim world by now - or are we looking at a small code addition to do this?

**Comment by SimonKrughoff** [comment]
I was actually suggesting that we let PhoSim generate the sky background.  The first block is the set of things I think we should not bother with and the second set seem like reasonable things for us to be able to handle.

Doing something like what you say would be possible and easy to do, but I'm not sure what we gain (other than compute time).

**Comment by drphilmarshall** [comment]
Ah, sorry - I misread your list. Yes, my suggestion of faking the
background noise was purely to save CPU time (but I understand it's a
significant saving, so guessed it was standard practice). It should
certainly be tied to OpSim.

BTW does the Twinkles field now avoid all bright stars? This is also an
important time (and data quality) saver.

**Comment by jchiang87** [comment]
In the cookbook, there is a 13th mag cut (for r band) that was applied to the instance catalogs fed to phosim.  I was planning to generate a sample of instance catalogs using Simon's [code/generatePhosimInput.py](https://github.com/DarkEnergyScienceCollaboration/Twinkles/blob/master/code/generatePhosimInput.py) for the various bands, and with various magnitude cuts, that we could use for benchmarking the phosim runs to help guide our choices on those items.   I'll make this an issue shortly.

**Comment by SimonKrughoff** [comment]
By the way, @jchiang87, you can put in a cut programmatically.  I believe it is the constraint keyword argument to the write_catalog method.  So it should be something like:
`constraint='rmag>14.'`

**Comment by sethdigel** [comment]
The [Physics Override Commands for PhoSim](https://confluence.lsstcorp.org/display/PHOSIM/Physics+Override+Commands) plus Table 7.15 of the [PhoSim Reference Guide](http://basov.physics.purdue.edu/lsst_sims/phosim_peterson_080213.pdf) (Device Properties) include all of the parameters that @SimonKrughoff mentioned except midline charge stop and brighter-fatter.  Maybe I'm just not recognizing the parameter names.  Also, do any of the other Physics Override options look like they should be invoked?

For reference here's Table 7.15:

Parameter | Value
-------------- | -------
full well depth | 100000
nbulk | 1012
nf | 0.0
ns | 5 × 10^15 
sb | 0.0025
sf | 0.01
edgeRolloffWidth | 10
edgeRolloffShift | 2.0
treeRingPeriod | 100.0
treeRingAmplitude | 0.15
treeRingRatio | 7.5
deadLayerDepth | 1.5
deadLayerWidth | 3000.0
deadLayerHeight | 500.0
deadLayerXoverlap | -200.0
deadLayerYoverlap | -200.0
deadLayerXinit 0 | 0.0
deadLayerXinit 1 | 300.0
deadLayerYinit 0 | 0.0
deadLayerYinit 1 | 300.0
deadLayerAngle 0 | 10.0
deadLayerAngle 1 | 10.0
pixelVarX | 0.003
pixelVarY | 0.002

**Comment by johnrpeterson** [comment]
Simon et al.-

This is an interesting topic.  Could you send a list of what you think the DM pipeline can’t handle but in terms of "image properties" rather than "physical aspects” as that is what really matters.  So instead of saying “clouds” you’d want to say something like "spatially-varying photometry”.  Then i could come up with a more complete list for this as there is not a trivial 1-to-1 mapping since there are emergent effects, etc.

As i side note, it is not obvious whether we should adopt this philosophy wholesale.  for instance, if you only include effects modelled by the stack you will underestimate your errors, whereas if you include unmodelled errors you overestimate them.  some of these things are of course subtle as well and it wouldn’t be a big deal to have them on even though DM doesn’t correct them (i.e. these are of course on in real data that is processed by DM).  probably to first order you’ll want to turn things off that cause major headaches.

john

**Comment by SimonKrughoff** [comment]
@johnrpeterson this is, unfortunately, fairly complicated.  I think the answer to your question is what you said in the last sentence.  We want to, for the time being, turn off things that will cause unnecessary headaches.  The reasons for this are varied: we have not coded the correction, we can correct but believe the residual would be uninteresting, we don't trust the model in phosim.

I'm not sure exactly how best to formalize that notion any more than the two of us have.  E.g. I want a spatially varying PSF, but I don't want spatially varying pixel size.  Both contribute to photometry, but are corrected for in different ways.

Maybe having a conversation would be useful.  @cwwalter is this something we could bring up in a SSim phonecon?

**Comment by johnrpeterson** [comment]
simon- but this sentence you say below is very helpful (i.e. you don’t want spatially-varying pixel size).  what else you don’t want is the key?  why don’t you want clouds, for instance?  we can do a phosim telecon about this, but think a little bit about what dm couldn’t handle at the moment.

> I'm not sure exactly how best to formalize that notion any more than the two of us have. E.g. I want a spatially varying PSF, but I don't want spatially varying pixel size.
>

**Comment by cwwalter** [comment]
> 
> I'm not sure exactly how best to formalize that notion any more than the two of us have. E.g. I want a spatially varying PSF, but I don't want spatially varying pixel size. Both contribute to photometry, but are corrected for in different ways.
> 
> Maybe having a conversation would be useful. @cwwalter is this something we could bring up in a SSim phonecon?
> 
Yes, we could definitely use a slot for this. You and John could lead the discussion.

-Chris

**Comment by SimonKrughoff** [comment]
@johnrpeterson I think it's more complicated than what DM can and can't correct for, at the moment.  It's more about how to separate things out so we can learn about one thing at a time.

Clouds, for example, are something I think we can deal with in DM, but I don't believe the model has been sufficiently vetted.  For these reasons, I don't think it will teach us anything to have them on.

Brighter/fatter, on the other hand, is something we do not have a pixel level correction for, so will only wash out signal we get by exploring other parameters.

I'll try to think about what we'd like to have turned on (it's easier for me to think that way than to think about what I'd like turned off).  Is there a comprehensive list of all the effects that go into the simulation to make it realistic?

**Comment by johnrpeterson** [comment]
> Clouds, for example, are something I think we can deal with in DM, but I don't believe the model has been sufficiently vetted. For these reasons, I don't think it will teach us anything to have them on.
> 
i’m not sure how you determined this and why you say clouds is not vetted.  so we need some more rigorous criterion here.

> Brighter/fatter, on the other hand, is something we do not have a pixel level correction for, so will only wash out signal we get by exploring other parameters.
> 
> I'll try to think about what we'd like to have turned on (it's easier for me to think that way than to think about what I'd like turned off). Is there a comprehensive list of all the effects that go into the simulation to make it realistic?
> 

yes, that is what i am getting at.  it is not easy to talk about “effects” because some are emergent. but i can try to put something together.  i’ll organize a meeting about this.

john

**Comment by SimonKrughoff** [comment]
>yes, that is what i am getting at.  it is not easy to talk about “effects” because some are emergent. but i >can try to put something together.  i’ll organize a meeting about this.
Please use the SSim slot for this meeting.  I think this week is even open.  I think all the relevant people have set that hour aside and I'd like to avoid trying to fit another meeting slot in.

**Comment by johnrpeterson** [comment]
> On Dec 8, 2015, at 2:35 PM, SimonKrughoff <notifications@github.com> wrote:
> 
> yes, that is what i am getting at. it is not easy to talk about “effects” because some are emergent. but i >can try to put something together. i’ll organize a meeting about this.
> Please use the SSim slot for this meeting. I think this week is even open. I think all the relevant people have set that hour aside and I'd like to avoid trying to fit another meeting slot in.
> 

can’t because have a students prelim then.  i will set up something later.  in the meantime, if you can dig up any documentation about DM’s limitations of current stack that would be helpful.

john

**Comment by SimonKrughoff** [comment]
O.K.  Next week is open too, if that helps.

**Comment by SimonKrughoff** [comment]
@johnrpeterson here are some thoughts on motivating the different effects from a DM perspective.

All, please feel free to edit, add, or move things around.  This is just a start, but I hope it's helpful.

*Things I'm not worried about right now because I think they are fairly tractable:*
* bias
* dark current
* cross talk
* flat fielding
* fringing
* snap combination
* cloud obscuration

*Things I think are too complicated to deal with until we know we can do things to the expected level in their absence:*
* tree rings
* brighter/fatter
* pixel size distortions due to edge effects

*Things I think we should consider keeping in the first iteration of simulations because they are fundamental to the questions we are going to ask in a way that I don't think we learn much without including them:*
* saturation, blooming, and bleeding
* cosmic rays (as long as they are realistic)
* PSF created with realistic atmosphere
* a distribution of SNR (varying sky brightness)
* realistic astrometric perturbations: proper motion, parallax, etc. (I could be talked out of this)
* charge diffusion
* realistic response for all components in the system: mirrors, filters, detectors
* reasonable distribution and density of sources (leading to realistic blending)

*Things I'm ambivalent about because I'm not sure we will need to deal with them at any level (please correct me if I'm wrong):*
* residual annealing patterns
* pixel response non-uniformity (prnu)
* CTE
* hysteresis effects

**Comment by drphilmarshall** [comment]
Thanks, @SimonKrughoff 
@jchiang87 @tony-johnson @TomGlanzman let's show this to @boutigny when we talk with him, he may well have useful input for us.
